sudo: false

dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install:
  # Install conda
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes
  - conda update -y -n base conda setuptools
  - conda create -n ogusa-dev python=$TRAVIS_PYTHON_VERSION
  - source activate ogusa-dev
  - conda env update -f environment.yml
  - pip install codecov
  - pip install -e .

# command to run tests, e.g. python setup.py test
script:
  - python -c "import ogusa"; coverage run -m pytest -s -v -m 'not full_run and not regression'

after_success:
  - codecov
