name: ospcdyn
channels:
- ospc
dependencies:
- python>=3.6
- setuptools
- mkl
- scipy>=0.18.1
- matplotlib
- numba
- numpy>=1.12.1
- pandas>=0.20.1
- pytest
- pytest-pep8
- pytest-xdist
- dask
- bokeh
- pip:
  - pyzmq
  - msgpack
